"""Generate the static, interactive visualizer demo published to GitHub Pages.

The snapshot below mirrors a **real end-to-end run** OSS-Agent performed against an
owned sandbox repository (``maharshi-coding/oss-agent-sandbox`` issue #3 -> PR #4),
where the local implementation was generated by the live Claude backend, validated
by real ``python -m pytest`` (5/5), reviewed, explained by a grounded learning
report, and carried through the human-approval gate. The sandbox is private, so the
PR is shown by number without a (dead) external link -- the data itself is genuine,
not invented timer activity.

Run: ``python scripts/build_demo.py`` -> writes ``docs/index.html``.
"""

from __future__ import annotations

from pathlib import Path

from oss_agent.domain.enums import (
    AgentName,
    ContributionType,
    Difficulty,
    EventType,
    MaintainerVerdict,
    Recommendation,
    ReviewVerdict,
    SuitabilityCategory,
    WorkflowState,
)
from oss_agent.domain.models import (
    CommandOutcome,
    ContributionScore,
    FileChange,
    ImplementationPlan,
    ImplementationResult,
    IssueAnalysis,
    LearningReport,
    MaintainerReview,
    PenaltyComponent,
    PlanStep,
    PullRequestResult,
    Repository,
    RepositoryReport,
    ReviewResult,
    ScoreComponent,
    SecurityResult,
    SuitabilityAssessment,
    TestResult,
    TestSuiteResult,
    WorkflowEvent,
    WorkflowSnapshot,
)
from oss_agent.observability.visualizer import render_html

REPO = "maharshi-coding/oss-agent-sandbox"
ISSUE = 3
BRANCH = "fix/issue-3"


def _snapshot() -> WorkflowSnapshot:
    repo = Repository(
        owner="maharshi-coding",
        name="oss-agent-sandbox",
        default_branch="main",
        primary_language="Python",
        description="Owned sandbox used to validate the full OSS-Agent pipeline.",
        stars=0,
        open_issues=1,
        license="mit",
        archived=False,
    )
    report = RepositoryReport(
        repository=repo,
        summary="Small Python project with a real pytest suite; no CI configured.",
        has_readme=True,
        has_tests=True,
        has_ci=False,
        license="mit",
        build_system="python",
        package_managers=["pip"],
        test_command="python -m pytest",
        contributing_requirements=["Keep changes minimal and add a covering test."],
    )
    analysis = IssueAnalysis(
        repository_full_name=REPO,
        issue_number=ISSUE,
        summary="power() multiplies instead of exponentiating.",
        problem_statement="power(base, exp) returns base * exp instead of base ** exp.",
        expected_behavior="power(base, exp) returns base raised to the power exp.",
        acceptance_criteria=["power(2, 10) == 1024", "existing tests still pass"],
        affected_components=["calculator"],
        probable_files=["calculator.py"],
        contribution_type=ContributionType.BUG_FIX,
        difficulty=Difficulty.EASY,
        test_requirements=["a test asserting power() exponentiates"],
        ambiguity_score=0.15,
        complexity=0.2,
    )
    score = ContributionScore(
        repository_full_name=REPO,
        issue_number=ISSUE,
        summary="Clear, well-scoped bug fix with a reproducible failure.",
        overall=74.5,
        base_score=80.0,
        components=[
            ScoreComponent(dimension="skill_match", raw=0.9, weight=25, weighted=22.5,
                           explanation="Python bug fix matches the developer profile."),
            ScoreComponent(dimension="issue_clarity", raw=0.85, weight=20, weighted=17.0,
                           explanation="Exact expected behaviour is stated."),
            ScoreComponent(dimension="scope", raw=0.9, weight=15, weighted=13.5,
                           explanation="Single-function, single-file change."),
        ],
        penalties=[
            PenaltyComponent(name="no_ci", amount=5.5,
                             explanation="No CI to corroborate the fix upstream."),
        ],
        recommendation=Recommendation.PURSUE,
        explanation="Strong skill match and clarity; minor penalty for missing CI.",
    )
    suitability = SuitabilityAssessment(
        repository_full_name=REPO,
        issue_number=ISSUE,
        summary="Open, unassigned, no competing PR -- appropriate to contribute.",
        category=SuitabilityCategory.EXCELLENT,
        score=82.0,
        positives=[
            "Issue is open and unassigned.",
            "No existing or linked pull request.",
            "Change is small and self-contained.",
        ],
        explanation="No blockers; a focused fix here is welcome.",
    )
    plan = ImplementationPlan(
        repository_full_name=REPO,
        issue_number=ISSUE,
        summary="Replace the multiplication with exponentiation and cover it.",
        objective="Make power(base, exp) return base ** exp.",
        contribution_type=ContributionType.BUG_FIX,
        branch_name=BRANCH,
        affected_files=["calculator.py"],
        do_not_modify=["test_calculator.py"],
        steps=[
            PlanStep(order=1, description="Fix the power() operator in calculator.py",
                     target_files=["calculator.py"], rationale="Root cause of the wrong result."),
        ],
        test_plan=["python -m pytest"],
        acceptance_criteria=["power(2, 10) == 1024"],
        rollback_strategy="git checkout -- calculator.py to revert the one-line change.",
    )
    implementation = ImplementationResult(
        summary="Changed the operator in power(); scope clean.",
        plan_branch=BRANCH,
        files_changed=[FileChange(path="calculator.py", change_type="modified",
                                  additions=1, deletions=2)],
        unexpected_files=[],
        notes=["Implemented by the live Claude backend inside the isolated worktree."],
    )
    pytest_cmd = CommandOutcome(
        command=["python", "-m", "pytest"],
        cwd=".worktrees/fix-issue-3",
        exit_code=0,
        duration_seconds=2.31,
        stdout_tail="5 passed in 2.31s",
    )
    test_result = TestResult(
        repository_full_name=REPO,
        summary="Real pytest run: 5 passed.",
        suites=[TestSuiteResult(name="pytest", kind="unit", passed=True, tests_total=5,
                                tests_passed=5, tests_failed=0, command=pytest_cmd)],
    )
    code_review = ReviewResult(
        summary="Minimal, in-scope, covered by a test.",
        verdict=ReviewVerdict.APPROVE, scope_ok=True, tests_adequate=True,
    )
    security_review = SecurityResult(
        summary="No secrets, no injection, no dangerous calls.",
        verdict=ReviewVerdict.APPROVE, secrets_detected=False, prompt_injection_detected=False,
    )
    maintainer_review = MaintainerReview(
        summary="Correct fix, good test, follows conventions.",
        verdict=MaintainerVerdict.APPROVE,
        praise=["Root-caused precisely.", "One-line change with a covering test."],
    )
    learning = LearningReport(
        repository_full_name=REPO,
        issue_number=ISSUE,
        title="Why power() was wrong and how the one-line fix resolves it",
        what_was_broken="power() used '*' so it multiplied base by exp.",
        why_it_was_broken="The wrong operator was used for exponentiation.",
        how_discovered="Context selection located power (calculator.py:12) from the issue keywords.",
        files_that_matter=["calculator.py"],
        what_changed=["calculator.py (+1/-2): return base ** exp"],
        why_the_fix_works="'**' is Python's exponentiation operator, matching the spec.",
        tests_that_prove_it=["test_power", "test_power_larger"],
        concepts_to_understand=["Python arithmetic operators (* vs **)"],
    )
    pr = PullRequestResult(
        repository_full_name=REPO,
        issue_number=ISSUE,
        branch=BRANCH,
        number=4,
        url=None,  # sandbox is private; show the number without a dead external link
        title="Fix power() to exponentiate instead of multiply",
        body="Fixes #3. Replaces `base * exp` with `base ** exp` and keeps the suite green.",
        created=True,
    )

    events = [
        WorkflowEvent(type=EventType.WORKFLOW_CREATED, action=f"workflow created for {REPO}#{ISSUE}"),
        WorkflowEvent(type=EventType.AGENT_COMPLETED, agent=AgentName.ISSUE_ANALYZER,
                      action="issue analyzed: bug_fix, ambiguity 0.15"),
        WorkflowEvent(type=EventType.AGENT_COMPLETED, agent=AgentName.CONTRIBUTION_SCORER,
                      action="scored 74.5/100 -> PURSUE; suitability EXCELLENT"),
        WorkflowEvent(type=EventType.WORKTREE_CREATED, action=f"isolated worktree {BRANCH} created"),
        WorkflowEvent(type=EventType.AGENT_COMPLETED, agent=AgentName.IMPLEMENTER,
                      action="live Claude edit: calculator.py (+1/-2)"),
        WorkflowEvent(type=EventType.COMMAND_EXECUTED, action="python -m pytest -> 5 passed"),
        WorkflowEvent(type=EventType.AGENT_COMPLETED, agent=AgentName.MAINTAINER_SIMULATOR,
                      action="code/security/maintainer review: APPROVE"),
        WorkflowEvent(type=EventType.NOTE, action="human approval granted before submit"),
        WorkflowEvent(type=EventType.PR_CREATED, action="PR #4 opened (base=main <- fix/issue-3)"),
    ]

    return WorkflowSnapshot(
        id="sandbox-issue-3",
        state=WorkflowState.PR_MONITORING,
        repository_full_name=REPO,
        issue_number=ISSUE,
        branch=BRANCH,
        worktree_path=".worktrees/fix-issue-3",
        repository=repo,
        repository_report=report,
        issue_analysis=analysis,
        score=score,
        suitability=suitability,
        plan=plan,
        implementation=implementation,
        test_result=test_result,
        code_review=code_review,
        security_review=security_review,
        maintainer_review=maintainer_review,
        learning_report=learning,
        pull_request=pr,
        human_approved=True,
        human_decision_note="Reviewed the diff and learning report; fix is correct.",
        events=events,
    )


def main() -> None:
    html = render_html(_snapshot())
    out = Path(__file__).resolve().parent.parent / "docs" / "index.html"
    out.write_text(html, encoding="utf-8")
    print(f"wrote {out} ({len(html):,} bytes)")


if __name__ == "__main__":
    main()
